deadlines:
  '3':
    Thu:
      date: 2025/01/30 11:00am
      content: a0
  '6':
    Tue:
      date: 2025/02/18 11:00am
      content: a1
  '8':
    Thu:
      date: 2025/03/06 11:00am
      content: a2
  '12':
    Tue:
      date: 2025/04/01 11:00am
      content: a3
  '15':
    Tue:
      date: 2025/04/22 11:00am
      content: a4
dates:
  firstMonday: 2025/01/13
  numWeeks: 17
types:
  default:
    className: lesson
  holiday:
    className: holiday
